package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/margostino/openearth/graph/model"
)

// Datasets is the resolver for the datasets field.
func (r *queryResolver) Datasets(ctx context.Context) ([]*model.Dataset, error) {
	datasetMock := &model.Dataset{
		Name:        "Mock dataset",
		Description: "This is a mock",
	}
	datasets := []*model.Dataset{datasetMock}
	return datasets, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
