// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dataset struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Category    string         `json:"category"`
	Source      *DatasetSource `json:"source"`
	URL         string         `json:"url"`
	LastUpdated string         `json:"last_updated"`
}

type DatasetSource struct {
	URL  string `json:"url"`
	Name string `json:"name"`
}

type NasaEarthData struct {
	URL         string                `json:"url"`
	Rss         string                `json:"rss"`
	Description string                `json:"description"`
	Topics      []*NasaEarthDataTopic `json:"topics"`
}

type NasaEarthDataTopic struct {
	Name        string                `json:"name"`
	URL         string                `json:"url"`
	Rss         string                `json:"rss"`
	Description string                `json:"description"`
	Subtopics   []*NasaEarthDataTopic `json:"subtopics"`
}

type NasaRssFeed struct {
	FeedType string `json:"feed_type"`
	Name     string `json:"name"`
	URL      string `json:"url"`
}
